### ISSUE TITLE
Snapshot functionallity

### ISSUE THREAD

**Issue by alexandrugavril** [valentinbuza/room-sketcher#3]
Salvarea unui png cu continutul camerei.

**Comment by raresmihait** [comment]
Trebuie schimbat iconul pentru ca nu am reusit sa pun unul de pe google. Pentru a schimba iconul:
1) adaugat in resources/images/icons
2) modificat in resources/scss/modules/_icons.scss la ".icon-download" din "dog.png" in noul "icon_name.png"
